---
- name: add tomcat group
  group:
    name: "{{ tomcat_group }}"

- name: add tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    home: "{{ tomcat_home }}"
    shell: /bin/false

- name: create /opt/tomcat directory
  file:
    path: "{{ tomcat_home }}"
    state: directory
    mode: 0755

- name: download & unarchive
  unarchive:
    src: http://apachemirror.wuchna.com/tomcat/tomcat-{{ ver }}/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz
    dest: "{{ tomcat_home }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Change ownership
  file:
    path: "{{ tomcat_home }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0755
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify: start tomcat

