---
- name: update your apt-get package
  apt:
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install tomcat for Debian
  include_tasks: installation.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: update your yum-get package
  yum:
    update_cache: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: install tomcat for Debian
  include_tasks: installation.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
